# Generated by Django 2.1 on 2018-10-18 02:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('operator_time', models.DateTimeField(default=datetime.datetime(2018, 10, 18, 2, 56, 34, 551529, tzinfo=utc))),
                ('content', models.TextField()),
                ('ip', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xauth_system_history',
            },
        ),
        migrations.CreateModel(
            name='SystemMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('activate', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('style', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentMenu', to='xauth.SystemMenu')),
            ],
            options={
                'db_table': 'xauth_system_menu',
                'ordering': ['order'],
            },
        ),
    ]
