# Generated by Django 2.1 on 2018-10-18 03:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemhistory',
            name='operator_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 3, 28, 45, 780919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='systemmenu',
            name='style',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
