# Generated by Django 2.1 on 2018-10-19 02:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0004_auto_20181019_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemhistory',
            name='operator_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 2, 10, 35, 728045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='systemmenu',
            name='action',
            field=models.CharField(help_text='父菜单可以为空', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='systemmenu',
            name='style',
            field=models.CharField(help_text='子菜单没有图标', max_length=255, null=True),
        ),
    ]
