# Generated by Django 2.1 on 2018-10-19 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_auto_20181019_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmenu',
            options={'ordering': ['parent_id', 'order']},
        ),
        migrations.AlterField(
            model_name='systemhistory',
            name='operator_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 6, 11, 33, 854772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='systemmenu',
            name='style',
            field=models.CharField(blank=True, choices=[('home', 'icon-home'), ('basket', 'icon-basket'), ('rocket', 'icon-rocket'), ('rocket', 'icon-diamond'), ('rocket', 'icon-puzzle'), ('paper-plane', 'icon-paper-plane'), ('settings', 'icon-settings'), ('briefcase', 'icon-briefcase'), ('wallet', 'icon-wallet'), ('bar-chart', 'icon-bar-chart'), ('docs', 'icon-docs'), ('present', 'icon-present'), ('folder', 'icon-folder'), ('user', 'icon-user'), ('pointer', 'icon-pointer')], help_text='子菜单没有图标', max_length=255),
        ),
    ]
