# Generated by Django 2.1 on 2018-10-15 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuserrelation',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
