# Generated by Django 2.1 on 2018-10-15 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daigo', '0003_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 8, 27, 25, 302942, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='no',
            field=models.IntegerField(unique=True),
        ),
    ]
