# Generated by Django 2.1 on 2018-10-15 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daigo', '0004_auto_20181015_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datetime',
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 8, 35, 21, 721565, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(default=1),
        ),
    ]
