# Generated by Django 2.1 on 2018-10-16 02:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daigo', '0005_auto_20181015_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderuserrelation',
            old_name='userId',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 2, 30, 30, 916661, tzinfo=utc)),
        ),
    ]
