# Generated by Django 2.1 on 2018-10-16 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daigo', '0006_auto_20181016_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 2, 53, 27, 381792, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='orderuserrelation',
            table='daigo_order_user_relation',
        ),
    ]
