# Generated by Django 2.1 on 2018-10-16 03:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daigo', '0007_auto_20181016_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_datetime']},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 3, 1, 49, 175965, tzinfo=utc)),
        ),
    ]
